// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjiMKRAZWWkmSCa99wIbZNDfIpFnOyGD8',
    appId: '1:780459309628:web:3ad7001540b8486aefe139',
    messagingSenderId: '780459309628',
    projectId: 'canatoybase',
    authDomain: 'canatoybase.firebaseapp.com',
    storageBucket: 'canatoybase.firebasestorage.app',
    measurementId: 'G-24JZ4NPRTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3cfXKTNaPv9W6QzGehPA_GHi3kiqrKoo',
    appId: '1:780459309628:android:aa78d478de8ad77aefe139',
    messagingSenderId: '780459309628',
    projectId: 'canatoybase',
    storageBucket: 'canatoybase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlErBNbsANFmLy7Z2LegEb8509BQce8Y',
    appId: '1:780459309628:ios:6bf97a447dfc9ae4efe139',
    messagingSenderId: '780459309628',
    projectId: 'canatoybase',
    storageBucket: 'canatoybase.firebasestorage.app',
    iosBundleId: 'com.example.cookieFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlErBNbsANFmLy7Z2LegEb8509BQce8Y',
    appId: '1:780459309628:ios:f692fd0b813a8b4befe139',
    messagingSenderId: '780459309628',
    projectId: 'canatoybase',
    storageBucket: 'canatoybase.firebasestorage.app',
    iosBundleId: 'com.example.cookieFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjiMKRAZWWkmSCa99wIbZNDfIpFnOyGD8',
    appId: '1:780459309628:web:285ac00d71e72cf3efe139',
    messagingSenderId: '780459309628',
    projectId: 'canatoybase',
    authDomain: 'canatoybase.firebaseapp.com',
    storageBucket: 'canatoybase.firebasestorage.app',
    measurementId: 'G-BHVPEJHJM7',
  );

}